export type BrazilianBank = {
  code: string;
  name: string;
};

export const brazilianBanks: BrazilianBank[] = [
  { code: "001", name: "BANCO DO BRASIL S.A." },
  { code: "033", name: "BANCO SANTANDER (BRASIL) S.A." },
  { code: "104", name: "CAIXA ECONOMICA FEDERAL" },
  { code: "237", name: "BANCO BRADESCO S.A." },
  { code: "260", name: "NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO" },
  { code: "341", name: "ITAÚ UNIBANCO S.A." },
  { code: "077", name: "BANCO INTER S.A." },
  { code: "041", name: "BANCO DO ESTADO DO RIO GRANDE DO SUL S.A." },
  { code: "004", name: "BANCO DO NORDESTE DO BRASIL S.A." },
  { code: "021", name: "BANCO BANESTES S.A." },
  { code: "070", name: "BANCO DE BRASILIA S.A." },
  { code: "197", name: "STONE PAGAMENTOS S.A." },
  { code: "208", name: "BANCO BTG PACTUAL S.A." },
  { code: "212", name: "BANCO ORIGINAL S.A." },
  { code: "218", name: "BANCO BS2 S.A." },
  { code: "290", name: "PAGSEGURO INTERNET S.A." },
  { code: "323", name: "MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA." },
  { code: "336", name: "BANCO C6 S.A." },
  { code: "389", name: "BANCO MERCANTIL DO BRASIL S.A." },
  { code: "422", name: "BANCO SAFRA S.A." },
  { code: "633", name: "BANCO RENDIMENTO S.A." },
  { code: "655", name: "BANCO VOTORANTIM S.A." },
  { code: "707", name: "BANCO DAYCOVAL S.A." },
  { code: "735", name: "BANCO NEON S.A." },
  { code: "739", name: "BANCO CETELEM S.A." },
  { code: "748", name: "BANCO COOPERATIVO SICREDI S.A." },
  { code: "756", name: "BANCO COOPERATIVO SICOOB S.A." },
  { code: "016", name: "COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES" },
  { code: "025", name: "BANCO ALFA S.A." },
  { code: "036", name: "BANCO BMG S.A." },
  { code: "047", name: "BANCO BANESE S.A." },
  { code: "065", name: "BANCO ANDBANK (BRASIL) S.A." },
  { code: "074", name: "BANCO J. SAFRA S.A." },
  { code: "085", name: "COOPERATIVA CENTRAL DE CRÉDITO - AILOS" },
  { code: "094", name: "BANCO FINAXIS S.A." },
  { code: "096", name: "BANCO B3 S.A." },
  { code: "119", name: "BANCO WESTERN UNION DO BRASIL S.A." },
  { code: "121", name: "BANCO GERAÇÃO DE FUTURO S.A." },
  { code: "125", name: "PLURAL S.A. BANCO MULTIPLO" },
  { code: "184", name: "BANCO ITAÚBA S.A." },
  { code: "244", name: "BANCO CORRETORA VALORES S.A." },
  { code: "318", name: "BANCO BMG S.A." },
  { code: "320", name: "CHINA CONSTRUCTION BANK (BRASIL) S.A." },
  { code: "321", name: "SOCIEDADE DE CRÉDITO DIRETO S.A." },
  { code: "332", name: "ACESSO SOLUÇÕES DE PAGAMENTO S.A." },
  { code: "366", name: "BANCO SOCIETE GENERALE BRASIL S.A." },
  { code: "399", name: "KIRTON BANK S.A. - BANCO MULTIPLO" },
  { code: "412", name: "BANCO CAPITAL S.A." },
  { code: "456", name: "BANCO MUFG BRASIL S.A." },
  { code: "464", name: "BANCO SUMITOMO MITSUI BRASIL S.A." },
  { code: "473", name: "BANCO CAIXA GERAL - BRASIL S.A." },
  { code: "477", name: "CITIBANK N.A." },
  { code: "479", name: "BANCO ITAUBANK S.A." },
  { code: "487", name: "DEUTSCHE BANK S.A. - BANCO ALEMAO" },
  { code: "488", name: "JPMORGAN CHASE BANK, NATIONAL ASSOCIATION" },
  { code: "492", name: "ING BANK N.V." },
  { code: "494", name: "BANCO REPREZENTACAO S.A." },
  { code: "495", name: "BANCO LA PROVINCIA DE BUENOS AIRES" },
  { code: "505", name: "BANCO CREDIT SUISSE (BRASIL) S.A." },
  { code: "574", name: "A55 SOCIEDADE DE CRÉDITO DIRETO S.A." },
  { code: "600", name: "BANCO LUSO BRASILEIRO S.A." },
  { code: "604", name: "BANCO INDUSTRIAL DO BRASIL S.A." },
  { code: "610", name: "BANCO VR S.A." },
  { code: "611", name: "BANCO PAULISTA S.A." },
  { code: "612", name: "BANCO GIBI S.A." },
  { code: "613", name: "BANCO PECUNIA S.A." },
  { code: "623", name: "BANCO PAN S.A." },
  { code: "626", name: "BANCO FICSA S.A." },
  { code: "630", name: "BANCO INTERCAP S.A." },
  { code: "634", name: "BANCO TRIANGULO S.A. (BANCO TRIANGULO)" },
  { code: "637", name: "BANCO SOFISA S.A." },
  { code: "643", name: "BANCO PINE S.A." },
  { code: "644", name: "SOCIEDADE DE CRÉDITO DIRETO S.A." },
  { code: "652", name: "BANCO ITAÚ HOLDING FINANCEIRA S.A." },
  { code: "653", name: "BANCO INDUSVAL S.A." },
  { code: "654", name: "BANCO A.J. RENNER S.A." },
  { code: "663", name: "ACTUAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A." },
  { code: "719", name: "BANCO BANIF PRIMUS S.A." },
  { code: "720", name: "BANCO MAXIMA S.A." },
  { code: "741", name: "BANCO RIBEIRAO PRETO S.A." },
  { code: "743", name: "BANCO SEMEAR S.A." },
  { code: "745", name: "BANCO CITIBANK S.A." },
  { code: "746", name: "BANCO MODAL S.A." },
  { code: "747", name: "BANCO RABOBANK INTERNATIONAL BRASIL S.A." },
  { code: "752", name: "BANCO BNP PARIBAS BRASIL S.A." },
  { code: "753", name: "BANCO COMMERCIAL INVESTMENT TRUST DO BRASIL S.A." },
  { code: "755", name: "BOFA MERRILL LYNCH BANCO MULTIPLO S.A." },
  { code: "769", name: "99PAY INSTITUICAO DE PAGAMENTO S.A." }
];
